In [1]:
import pandas as pd
import tqdm
import numpy as np
import codecs
import glob
import random
import matplotlib.pyplot as plt
import sys
from wordcloud_functions import *

In [136]:
#liar_coefs = pd.read_csv("liar_TEST_coefs_10000feats_5gram-l1.csv", sep='\t') # six-class Liar

kaggle = pd.read_csv("NEW_kaggle_coefs_final.csv", sep='\t') # train set coefs

#liar = pd.read_csv("NEW_liar_coefs_final.csv", sep='\t') # coefs from train set

#FakeNewsNet = pd.read_csv("FakeNewsNet_coefs_final.csv", sep='\t')

#liar_valid = pd.read_csv("liar_valid_coefs_final.csv", sep='\t') # coefs from validation set

#liar_random = pd.read_csv("liar_test_shuffled_labels_coefs_final.csv", sep='\t') #coefs from test set with random labels

#liar_split1 = pd.read_csv("liar_split1_coefs.csv", sep='\t')
#liar_split2 = pd.read_csv("liar_split2_coefs.csv", sep='\t')
liar_split1 = pd.read_csv("NEW_liar_train_split1_coefs.csv", sep='\t')
liar_split2 = pd.read_csv("NEW_liar_train_split2_coefs.csv", sep='\t')

liar_random = pd.read_csv("NEW_liar_testanddev_random_labels.csv", sep='\t') #liar valid and test concatenated

#testing_rand = pd.read_csv("testing_random_labels_coefs_on_larger_data.csv", sep="\t") # envestigating whether more data makes coefficients more expressive with random labels.
#politifact = pd.read_csv("politifact_coefs.csv", sep="\t")
#snopes = pd.read_csv("snopes_coefs.csv", sep="\t")

FakeNewsCorpus = pd.read_csv("NEW_FakeNewsCorpus_coefs.csv", sep='\t')

In [118]:
#classes = ['barely-true', 'false','half-true', 'mostly-true', 'pants-fire', 'true']
#liar_coefs.columns = [s.replace('_', ' ') for s in liar_coefs.columns]

#print(len(liar_coefs))
#print(len(classes))

#liar_coefs["class_labels"] = classes
#liar_coefs.set_index("class_labels", inplace=True)
#liar_coefs = liar_coefs.T
#false = liar_coefs.sort_values(by='false', ascending=False)
#false = false["false"]
#print(false.head(10))
#print(false.tail(10))

In [119]:
# find "best features" through highest coefficients of binary data

In [120]:
kaggle.columns = [s.replace('_', ' ') for s in kaggle.columns]
#kaggle_coefs.T.sort_values(by=0, ascending=False).tail(20)
kaggle.T.sort_values(by=0, ascending=False).tail(30)

                         0
comment         -24.662021
based           -24.785528
right           -25.518988
corrupt         -25.882223
the us          -26.184447
however         -26.631717
population      -28.432219
master          -28.460684
al              -30.711227
elect           -30.794353
so called       -31.333690
26              -32.279951
hillary         -33.114994
pro             -33.833548
president elect -33.912333
click           -36.083378
print           -36.657517
via             -36.724916
source          -36.820784
november 2016   -36.896034
us              -37.830128
share           -41.171381
november        -48.626680
self            -51.465532
co              -55.820289
2016            -60.560375
year old        -62.419340
non             -63.290661
october         -66.038891
anti            -70.548679

In [137]:
#liar.columns = [s.replace('_', ' ') for s in liar.columns]
#liar.T.sort_values(by=0, ascending=False).tail(20)
#liar.T.sort_values(by=0, ascending=False).head(30)

In [138]:
#liar_valid.columns = [s.replace('_', ' ') for s in liar_valid.columns]
#liar_valid.T.sort_values(by=0, ascending=False).tail(20)
#liar_valid.T.sort_values(by=0, ascending=False).head(30)

In [123]:
liar_random.columns = [s.replace('_', ' ') for s in liar_random.columns]
liar_random.T.sort_values(by=0, ascending=False).head(20)

                             0
has not              27.982093
cause                24.126928
in texas             24.121026
investigation        23.058847
of florida           22.771562
environmental        22.558729
worse                22.088678
years in             21.932334
presidency           21.439044
taxes on             21.190351
rose                 21.112520
bathroom             21.075159
to make              21.026966
insurance            20.941589
and in               20.840964
down the             20.518376
insurance companies  20.282669
total                20.122748
amendment            19.970864
spend                19.945649

In [124]:
liar_split1.columns = [s.replace('_', ' ') for s in liar_split1.columns]
liar_split1.T.sort_values(by=0, ascending=False).head(50)

                           0
expanded           55.323105
general            50.752288
in more            50.485996
piece              50.469733
for people         48.858599
went down          48.688106
for the same       48.195263
strikes            46.453472
and all            45.626368
bill in            45.275469
fish               44.959180
for all            43.570548
lawyer             42.947143
hands              41.904592
act is             41.691657
between            41.442007
has voted          40.675675
right to work      40.467174
standards          40.258716
the gop            40.239366
not only           40.154672
offshore drilling  39.851929
last in            39.601278
whos               39.485021
shutdown           39.273082
as the             39.030537
that people        38.855280
audit              38.845098
generation         38.518283
their own          38.352597
in iraq            38.071795
can still          37.967655
says jeff          37.904460
square             37.825104
dream              37.803866
year for           37.474808
charges            37.321100
nationally         37.186807
of small           36.911847
budget that        36.761803
agree              36.663959
floor              36.335838
than in the        36.260612
of white           36.240489
believe in         36.202182
crisis             36.175100
tested             36.061395
fortune            36.058888
82                 36.019011
for education      35.911041

In [125]:
liar_split2.columns = [s.replace('_', ' ') for s in liar_split2.columns]
liar_split2.T.sort_values(by=0, ascending=False).head(100)

                             0
bill to              60.094373
corporations         49.729705
photo                49.594229
caused by            46.652449
60 000               45.685891
internet             45.238878
jobs to              45.149583
fatalities           43.254425
percent of the time  42.550067
limits               41.759976
voted to let         41.733869
country in           41.273742
to let               39.799406
street               39.371640
in three             39.071463
51                   38.771127
deported             38.746865
40 years             38.269342
together             38.253077
happened             37.681962
of the republican    37.147112
new private          37.093862
twenty               36.718930
decided              36.684991
budget in            36.617261
its not              36.252779
payroll              35.965481
in five              35.685935
on our               35.666526
biggest              35.646458
...                        ...
will have            32.089049
means                31.785340
000 year             31.736321
says rick            31.490740
problems             31.452571
income inequality    31.407515
countries            31.322333
700 billion          31.244635
says some            31.199902
alaska               31.184706
14                   31.101756
if you               31.063424
trillion             31.052916
did in               30.909888
trust                30.878673
average              30.774783
put                  30.679146
science              30.630648
transit              30.620856
money and            30.559850
to other             30.559521
first year           30.504626
successful           30.378772
entire               30.371520
should not           30.370810
shows that           30.315359
the midwest          30.271527
in november          30.217458
of the top           30.181126
separate             30.127610

[100 rows x 1 columns]

In [139]:
#FakeNewsNet.columns = [s.replace('_', ' ') for s in FakeNewsNet.columns]
#FakeNewsNet.T.sort_values(by=0, ascending=False).tail(20)
#FakeNewsNet.T.sort_values(by=0, ascending=False).head(5)#.index.tolist()

In [127]:
# make common vocabulary (only shared words)
# Rank features med Mean reciprocal rank. Brug kun overlappende vocabulary mellem alle datasæt
# Prøv også Spearman rank order correlation:
# https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.stats.spearmanr.html
from scipy import stats
#stats.spearmanr(a, b)

In [128]:
# 1 = True
# 0 = Fake

In [129]:
# LIAR (ene halvdel) er Ground truth, selvom den selvfølgelig ikke er sand på nogen måde. 
# Og så MRR for LIAR (anden del), random labels, og de andre fake news datasets.

#def mean_reciprocal_rank(rs):
#    rs = (np.asarray(r).nonzero()[0] for r in rs)
#    return np.mean([1. / (r[0] + 1) if r.size else 0. for r in rs])

#from sklearn.metrics import label_ranking_average_precision_score
# Label ranking average precision
#If there is exactly one relevant label per sample, label ranking average precision is equivalent to the mean reciprocal rank.

In [130]:
from sklearn.metrics import label_ranking_average_precision_score
from sklearn import preprocessing

def top_features(df, n=50, head=True):
    df.columns = [s.replace('_', ' ') for s in df.columns]
    if head==False:
        features_sorted = df.T.sort_values(by=0, ascending=False).tail(n)
    else:
        features_sorted = df.T.sort_values(by=0, ascending=False).head(n)
    features_list = features_sorted.index.tolist()
    coefs = features_sorted[0].tolist()
    tuples = [(f, np.around(c, decimals=3)) for f,c in zip(features_list, coefs)]
    return tuples

def common_words(df):
    liar_split1.columns = [s.replace('_', ' ') for s in liar_split1.columns]
    liar_feats = liar_split1.columns.tolist()
    df.columns = [s.replace('_', ' ') for s in df.columns]
    common_feats = [i for i in df.columns if i in liar_feats]
    print("number of common words:",len(common_feats))
    
    ground_truth = liar_split1[common_feats].T.sort_values(by=0, ascending=False).index.tolist()
    other = df[common_feats].T.sort_values(by=0, ascending=False).index.tolist()
    
    ground_truth_df = liar_split1[common_feats].T.sort_values(by=0, ascending=False)
    other_df = df[common_feats].T.sort_values(by=0, ascending=False)
    
    #ground_truth_coefs = liar_split1[common_feats].T.sort_values(by=0, ascending=False).values.tolist()
    #other_coefs = df[common_feats].T.sort_values(by=0, ascending=False).values.tolist()
    #print(other_coefs)
    
    # list coefficients of common words after liar's coeff order (ground truth)
    return ground_truth, other, common_feats, ground_truth_df, other_df#, ground_truth_coefs, other_coefs


def sort_other_by_ground_index(ground_truth_df, other_df):
    df1 = other_df
    df1 = df1.reindex(index=ground_truth_df.index)
    return df1



def MRR(df):
    ground_truth, other, common_feats, ground_truth_df, other_df = common_words(df)
    
    lb = preprocessing.LabelBinarizer()
    ground_truth = lb.fit_transform(ground_truth)
    other = lb.transform(other)
    mrr = label_ranking_average_precision_score(ground_truth, other)

    df1 = other_df
    df1 = df1.reindex(index=ground_truth_df.index)
    df_both = pd.concat([ground_truth_df, df1], axis=1)
    df_both.columns = ["Liar_split1_coefs", "Liar_split2_coefs"]
    #print(stats.spearmanr(df_both["Liar_split1_coefs"],df_both["Liar_split2_coefs"] ))
    spear = stats.spearmanr(df_both["Liar_split1_coefs"],df_both["Liar_split2_coefs"])
    kendall = stats.kendalltau(df_both["Liar_split1_coefs"],df_both["Liar_split2_coefs"])
    
    return kendall, spear, mrr

In [131]:
ground_truth, other, common_feats, ground_truth_df, other_df = common_words(liar_random)

number of common words: 3278

In [132]:
df1 = other_df
df1 = df1.reindex(index=ground_truth_df.index)
df_both = pd.concat([ground_truth_df, df1], axis=1)
df_both.columns = ["Liar_split1_coefs", "Liar_split2_coefs"]
print(stats.spearmanr(df_both["Liar_split1_coefs"],df_both["Liar_split2_coefs"] ))
df_both

SpearmanrResult(correlation=-0.001346361813274133, pvalue=0.938579796711495)

                 Liar_split1_coefs  Liar_split2_coefs
general                  50.752288           1.704846
for people               48.858599          -3.284167
bill in                  45.275469          -7.232064
for all                  43.570548          -2.249774
hands                    41.904592          -4.043879
between                  41.442007         -17.116096
has voted                40.675675         -15.561382
right to work            40.467174         -10.004677
not only                 40.154672          -7.052606
last in                  39.601278           1.817379
whos                     39.485021           2.781764
as the                   39.030537          -4.870258
audit                    38.845098          11.359485
their own                38.352597          -2.702741
in iraq                  38.071795          -2.453148
dream                    37.803866          -3.216698
charges                  37.321100           1.228663
budget that              36.761803           8.594389
than in the              36.260612          -7.884948
crisis                   36.175100          15.085978
for education            35.911041           1.163811
clinton was              35.887826           0.665064
fiscal year              35.884374          -9.149539
65                       35.833756          -2.706891
says that in             35.524429          17.363059
24                       35.457175           0.232993
college                  35.194797          -0.237844
the other                34.987344           6.344131
research                 34.926769           6.038832
in the nation            34.731320          -2.474005
...                            ...                ...
in office               -33.914654         -13.894783
up the                  -33.937325           1.884413
card                    -34.044280         -11.855091
are out                 -34.066983           0.317858
seven years             -34.165237          -7.224284
either                  -34.191497         -10.230171
increase in the         -34.295878          -3.987809
pledge                  -34.333393          -0.258379
they dont               -34.583140           3.251767
in 2013                 -34.792450          -8.638015
state senate            -35.328350          -6.418535
prices                  -35.802444           6.048085
the wisconsin           -36.309769          -0.234846
to his                  -36.321605          -7.431431
the second              -36.344604           4.191302
loan                    -36.417238         -17.623793
during his              -36.779966          -8.768167
says bill               -38.123732           9.637604
tea                     -38.501370          -1.213599
benghazi                -39.144747         -10.377649
over half               -39.712781           7.523245
was in                  -40.555162         -14.414202
of the states           -40.829049           2.619902
per year                -41.215893          -5.642665
governments             -41.392231           0.547788
says charlie            -42.999183          12.597770
country that            -43.574845           5.107778
spending in             -44.280928          -5.166034
impose                  -44.692535          -3.055944
holding                 -47.314712          -8.040086

[3278 rows x 2 columns]

In [140]:
#ground_truth

In [134]:
ls = top_features(FakeNewsCorpus, n=20, head=False)
print(ls[::-1])

[('going on many', -63.521), ('next by', -49.936), ('article has been', -45.759), ('ps all rights reserved source', -37.356), ('there something else', -36.39), ('with the help', -35.805), ('and the day', -26.465), ('of christ and', -24.205), ('bitcoin blockchain', -23.982), ('other words', -23.674), ('this article has been', -23.331), ('understand the difference', -21.989), ('lord in', -21.014), ('in terms of', -20.247), ('los angeles', -19.539), ('republished with permission from', -19.249), ('the help of', -17.153), ('well as', -17.067), ('christ and the', -16.924), ('by lisa haven', -15.295)]

In [135]:
print("liar split 2")
print(MRR(liar_split2))
print()
print("liar random")
print(MRR(liar_random))
print()
print("kaggle")
print(MRR(kaggle))
print()
print("FakeNewsCorpus")
print(MRR(FakeNewsCorpus))

liar split 2
number of common words: 3567
(KendalltauResult(correlation=0.023055867040466062, pvalue=0.038977851315390756), SpearmanrResult(correlation=0.033932012021838334, pvalue=0.042719597409482224), 0.0002803476310625285)

liar random
number of common words: 3278
(KendalltauResult(correlation=-0.000949585836306722, pvalue=0.935041169839104), SpearmanrResult(correlation=-0.001346361813274133, pvalue=0.938579796711495), 0.0006100350628238496)

kaggle
number of common words: 2462
(KendalltauResult(correlation=-0.00034824613509729893, pvalue=0.9793366379128449), SpearmanrResult(correlation=-0.0005693181577948438, pvalue=0.9774752047893994), 0.00040617384240457276)

FakeNewsCorpus
number of common words: 2270
(KendalltauResult(correlation=0.0013874138691325646, pvalue=0.9210772588276923), SpearmanrResult(correlation=0.001862888936821248, pvalue=0.9293142657986271), 0.0004405286343612548)