In [96]:
import pandas as pd
import tqdm
import numpy as np
import codecs
import glob
import random
import matplotlib.pyplot as plt
import sys
from wordcloud_functions import *

In [128]:
#liar_coefs = pd.read_csv("liar_TEST_coefs_10000feats_5gram-l1.csv", sep='\t') # six-class Liar

kaggle = pd.read_csv("kaggle_coefs_final.csv", sep='\t') # train set coefs

liar = pd.read_csv("liar_coefs_final.csv", sep='\t') # coefs from train set

FakeNewsNet = pd.read_csv("FakeNewsNet_coefs_final.csv", sep='\t')

liar_valid = pd.read_csv("liar_valid_coefs_final.csv", sep='\t') # coefs from validation set

#liar_random = pd.read_csv("liar_test_shuffled_labels_coefs_final.csv", sep='\t') #coefs from test set with random labels

#liar_split1 = pd.read_csv("liar_split1_coefs.csv", sep='\t')
#liar_split2 = pd.read_csv("liar_split2_coefs.csv", sep='\t')
liar_split1 = pd.read_csv("liar_train_split1_coefs.csv", sep='\t')
liar_split2 = pd.read_csv("liar_train_split2_coefs.csv", sep='\t')

liar_random = pd.read_csv("liar_testanddev_random_labels.csv", sep='\t') #liar valid and test concatenated

#testing_rand = pd.read_csv("testing_random_labels_coefs_on_larger_data.csv", sep="\t") # envestigating whether more data makes coefficients more expressive with random labels.

In [111]:
#classes = ['barely-true', 'false','half-true', 'mostly-true', 'pants-fire', 'true']
#liar_coefs.columns = [s.replace('_', ' ') for s in liar_coefs.columns]

#print(len(liar_coefs))
#print(len(classes))

#liar_coefs["class_labels"] = classes
#liar_coefs.set_index("class_labels", inplace=True)
#liar_coefs = liar_coefs.T
#false = liar_coefs.sort_values(by='false', ascending=False)
#false = false["false"]
#print(false.head(10))
#print(false.tail(10))

In [112]:
# find "best features" through highest coefficients of binary data

In [113]:
kaggle.columns = [s.replace('_', ' ') for s in kaggle.columns]
#kaggle_coefs.T.sort_values(by=0, ascending=False).tail(20)
kaggle.T.sort_values(by=0, ascending=False).head(30)

                                0
president donald trump  44.419383
breitbart               33.262422
president trump         29.953989
follow                  26.090524
on twitter              24.048604
said                    20.267602
ms                      18.724870
mr                      18.390579
2017                    16.524177
sunday                  12.162331
ap                       9.029540
the 2016                 8.993441
new york                 8.459367
twitter                  7.320697
last year                7.207630
president donald         7.017092
in 2016                  6.969075
an                       6.859950
                         6.473593
march                    6.404286
saturday                 6.214272
on                       5.777907
its                      5.758600
milo                     5.605364
app                      5.473274
but                      5.287803
friday                   5.202065
jeff                     5.096164
administration           5.092549
spicer                   4.978871

In [114]:
liar.columns = [s.replace('_', ' ') for s in liar.columns]
#liar.T.sort_values(by=0, ascending=False).tail(20)
liar.T.sort_values(by=0, ascending=False).head(30)

                          0
than               3.943907
countries          3.942619
since              3.891896
percent            3.068167
day                3.032906
says donald trump  2.952451
average            2.883745
still              2.868666
georgia            2.601293
shutdown           2.490296
debt               2.387724
million            2.358784
lobbyists          2.310321
while the          2.300257
to do              2.250680
times              2.183326
months             2.103412
worth              2.067387
highest            2.009213
money from         1.991730
corporations       1.922233
he                 1.915460
cut                1.878987
says scott         1.866033
the country        1.835692
of                 1.832807
lower              1.819907
expanded           1.813954
twenty             1.803512
up to              1.763890

In [115]:
liar_valid.columns = [s.replace('_', ' ') for s in liar_valid.columns]
#liar_valid.T.sort_values(by=0, ascending=False).tail(20)
liar_valid.T.sort_values(by=0, ascending=False).head(30)

                                        0
than                             3.098273
more                             2.332862
has                              2.218518
half                             1.701111
percent                          1.250872
percent of                       1.124786
are                              1.080352
000                              0.921116
state                            0.844780
new                              0.824213
of                               0.698165
and                              0.667298
the                              0.654083
years                            0.559575
we                               0.463980
american                         0.168843
says the united states           0.000000
says there are                   0.000000
says the hospital listed on      0.000000
says the human                   0.000000
says the human rights            0.000000
says the human rights campaign   0.000000
says the inspector               0.000000
says the inspector general       0.000000
says the hospital                0.000000
says the inspector general for   0.000000
says the jurisdictions           0.000000
says the jurisdictions with      0.000000
says the jurisdictions with the  0.000000
says the kkk                     0.000000

In [127]:
liar_random.columns = [s.replace('_', ' ') for s in liar_random.columns]
liar_random.T.sort_values(by=0, ascending=False).tail(20)

                         0
had               0.000000
had an            0.000000
gun laws          0.000000
gun control laws  0.000000
percent          -0.171584
his              -0.198038
in america       -0.272560
in the           -0.388766
earmarks         -0.433953
americans        -0.449089
support          -0.571723
as               -0.674989
of               -0.913693
texas            -1.006270
economy          -1.055083
lost             -1.067633
jobs             -1.132274
million          -1.191901
congress         -1.406480
hillary clinton  -1.690667

In [121]:
liar_split1.columns = [s.replace('_', ' ') for s in liar_split1.columns]
liar_split1.T.sort_values(by=0, ascending=False).head(100)

                          0
than               3.796285
times              3.202611
since              3.056263
percent            2.846736
of                 2.429272
10                 2.182118
six                2.106106
more               2.100319
day                2.023203
says donald trump  1.989060
million            1.806124
the country        1.723671
college            1.682986
georgia            1.614375
highest            1.556499
weve               1.524551
deficit            1.505239
national debt      1.438493
percent of         1.374281
half               1.302133
every              1.252058
in the             1.223933
lower              1.182204
oil                1.177250
terms              1.171185
funding            1.146361
its                1.135504
cut                1.125928
called             1.093064
months             1.070401
...                     ...
against the        0.273604
county             0.260431
can be             0.242140
states             0.240499
made               0.218162
the no             0.194083
no                 0.170201
debt               0.168641
at                 0.163252
thirds             0.158593
two thirds         0.158593
the                0.153676
mitt romney        0.150522
education          0.148793
in the nation      0.146343
have               0.133645
down               0.129888
countries          0.092520
most               0.086535
romney             0.079215
school             0.078915
general            0.068817
higher             0.060885
republicans        0.058084
ago                0.053175
every day          0.048623
texas              0.046698
just               0.040567
says she           0.039763
gas                0.011906

[100 rows x 1 columns]

In [122]:
liar_split2.columns = [s.replace('_', ' ') for s in liar_split2.columns]
liar_split2.T.sort_values(by=0, ascending=False).head(100)

                   0
countries   4.055686
than        3.766869
three       3.653519
average     3.480996
since       3.389277
debt        3.359014
percent     2.962213
top         2.902746
photo       2.878002
still       2.825379
he          2.668234
romney      2.644196
day         2.497385
american    2.472366
georgia     2.343114
governor    2.097227
spending    2.088615
in          1.915682
this        1.887571
of the      1.776398
million     1.711684
crime       1.505420
cut         1.463854
the nation  1.446512
and         1.427428
minimum     1.340888
more        1.285802
put         1.157515
up          1.149712
mccain      1.041758
...              ...
with        0.372916
rate        0.342614
says mitt   0.342056
won         0.319707
have had    0.317718
money from  0.307113
school      0.288251
15          0.274030
iraq        0.268285
shutdown    0.262988
but         0.212030
times       0.204690
violence    0.197744
our         0.191851
almost      0.189130
americans   0.167670
act         0.157777
40          0.150594
own         0.138356
do          0.119819
background  0.111847
gun         0.111404
program     0.109874
14          0.106994
are         0.092352
now         0.088866
helped      0.086824
supported   0.083025
actually    0.070377
year        0.069181

[100 rows x 1 columns]

In [91]:
#FakeNewsNet.columns = [s.replace('_', ' ') for s in FakeNewsNet.columns]
#FakeNewsNet.T.sort_values(by=0, ascending=False).tail(20)
#FakeNewsNet.T.sort_values(by=0, ascending=False).tail(30)

In [21]:
# make common vocabulary (only shared words)
# Rank features med Mean reciprocal rank. Brug kun overlappende vocabulary mellem alle datasæt
# Prøv også Spearman rank order correlation:
# https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.stats.spearmanr.html
from scipy import stats
#stats.spearmanr(a, b)

In [ ]:
# 1 = True
# 0 = Fake

In [ ]:
def mean_reciprocal_rank(rs):
    rs = (np.asarray(r).nonzero()[0] for r in rs)
    return np.mean([1. / (r[0] + 1) if r.size else 0. for r in rs])